version: 0.1
phases:
  install:
    commands:
      - pip install -r requirements.txt -t libs
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket wi-processing 
                                   --output-template-file NewSamTemplate.yaml
artifacts:
  type: zip
  files:
    - NewSamTemplate.yaml
