Transform: 'AWS::Serverless-2016-10-31'
Parameters:
    SamMultipler:
        Description: "Wi-processing"
        Type: "String"
    OriginUrl:
        Description: "The origin url to allow CORS requests from. This will be the base URL of your static SAM website."
        Type: "String"
Resources:
    NumpyExample:
        Type: AWS::Serverless::Function
        Properties:
            Handler: index.handler
            Runtime: python2.7
            CodeUri: ./
            Environment:
                Variables:
                    SAM_MULTIPLIER: !Ref SamMultipler
                    ORIGIN_URL: !Ref OriginUrl
            Events:
              GetResource:
                Type: Api
                Properties:
                  Path: /numpyexample
                  Method: get
