AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Hello from aws lambda
Resources:
  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.hello
      Runtime: python2.7
      CodeUri: ./
      Events:
        HelloApi:
          Type: Api
          Properties:
            Path: /HelloResource
            Method: GET
